plugins {
    id 'groovy-gradle-plugin'
    id 'java-gradle-plugin'
}

repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()
}

allprojects {
    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, "minutes"
        resolutionStrategy.cacheDynamicVersionsFor 0, "minutes"
    }
}
